const fs = require('fs');
const path = require('path');

function processDir(dir) {
  const files = fs.readdirSync(dir, { withFileTypes: true });
  for (const file of files) {
    const fullPath = path.join(dir, file.name);
    if (file.isDirectory()) {
      processDir(fullPath);
    } else if (file.name.endsWith('.tsx') || file.name.endsWith('.ts')) {
      let content = fs.readFileSync(fullPath, 'utf8');
      const original = content;

      // 1. Replace Link hrefs
      // /student/subjects/${subjectId} -> /student/subjects/subject?subjectId=${subjectId}
      content = content.replace(/\/student\/subjects\/\$\{([^}]+)\}/g, (match, p1) => {
        // If it's just the subject
        return `/student/subjects/subject?subjectId=\${${p1}}`;
      });
      content = content.replace(/\/faculty\/subjects\/\$\{([^}]+)\}/g, (match, p1) => {
        return `/faculty/subjects/subject?subjectId=\${${p1}}`;
      });

      // Fix multiple query params (e.g., if there's already a ? we need to replace it with & and so on, but it's easier to just do targeted regex)
      // /student/subjects/subject?subjectId=${subjectId}/modules/${mod.id} -> /student/subjects/subject/modules/item?subjectId=${subjectId}&id=${mod.id}
      content = content.replace(/\/student\/subjects\/subject\?subjectId=\$\{([^}]+)\}\/modules\/\$\{([^}]+)\}\/simulations\/\$\{([^}]+)\}/g, 
        '/student/subjects/subject/modules/item/simulations/subtopic?subjectId=${$1}&id=${$2}&subtopicId=${$3}');
      
      content = content.replace(/\/student\/subjects\/subject\?subjectId=\$\{([^}]+)\}\/modules\/\$\{([^}]+)\}/g, 
        '/student/subjects/subject/modules/item?subjectId=${$1}&id=${$2}');

      content = content.replace(/\/student\/subjects\/subject\?subjectId=\$\{([^}]+)\}\/quizzes\/\$\{([^}]+)\}\/attempts\/\$\{([^}]+)\}/g, 
        '/student/subjects/subject/quizzes/item/attempts/attempt?subjectId=${$1}&id=${$2}&attemptId=${$3}');

      content = content.replace(/\/student\/subjects\/subject\?subjectId=\$\{([^}]+)\}\/quizzes\/\$\{([^}]+)\}/g, 
        '/student/subjects/subject/quizzes/item?subjectId=${$1}&id=${$2}');

      content = content.replace(/\/student\/subjects\/subject\?subjectId=\$\{([^}]+)\}\/simulations\/\$\{([^}]+)\}/g, 
        '/student/subjects/subject/simulations/item?subjectId=${$1}&id=${$2}');

      content = content.replace(/\/student\/subjects\/subject\?subjectId=\$\{([^}]+)\}\/flashcards\/\$\{([^}]+)\}/g, 
        '/student/subjects/subject/flashcards/item?subjectId=${$1}&id=${$2}');

      // Faculty equivalents
      content = content.replace(/\/faculty\/subjects\/subject\?subjectId=\$\{([^}]+)\}\/([a-zA-Z0-9-]+)/g, 
        '/faculty/subjects/subject/$2?subjectId=${$1}');


      // 2. Replace params usage with useSearchParams
      // This is trickier, but most use(params) were generated by our split script or written as:
      // const { subjectId } = use(params);
      // Let's replace:
      // import { use } from "react"; -> import { useSearchParams, Suspense } from "next/navigation";
      if (fullPath.includes('ClientPage.tsx')) {
        if (!content.includes('useSearchParams')) {
          content = content.replace(/import {([^}]+)} from "react";/, (m, p1) => {
            return `import { useSearchParams } from "next/navigation";\nimport {${p1}} from "react";`;
          });
          if (!content.includes('useSearchParams')) {
             content = `import { useSearchParams } from "next/navigation";\n` + content;
          }
        }

        // Replace const { subjectId } = use(params);
        content = content.replace(/const\s+\{\s*([a-zA-Z0-9_,\s]+)\s*\}\s*=\s*use\(params\);/g, (match, vars) => {
          const variables = vars.split(',').map(v => v.trim()).filter(Boolean);
          let replacements = `const searchParams = useSearchParams();\n`;
          for (const v of variables) {
            replacements += `  const ${v} = searchParams.get('${v}');\n`;
          }
          return replacements;
        });

        // Replace const { subjectId } = params;
        content = content.replace(/const\s+\{\s*([a-zA-Z0-9_,\s]+)\s*\}\s*=\s*params;/g, (match, vars) => {
          const variables = vars.split(',').map(v => v.trim()).filter(Boolean);
          let replacements = `const searchParams = useSearchParams();\n`;
          for (const v of variables) {
            replacements += `  const ${v} = searchParams.get('${v}');\n`;
          }
          return replacements;
        });
      }

      if (content !== original) {
        fs.writeFileSync(fullPath, content, 'utf8');
        console.log('Refactored links/params in:', fullPath);
      }
    }
  }
}

processDir(path.join(__dirname, 'src/app'));
console.log('Finished link refactoring.');
